[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
http = { workspace = true }
tracing = {workspace = true}
tokio = { workspace=true }

[build-dependencies]
curl = "0.4.49"
tokio = { workspace=true }
